### PR TITLE
Add env to disable gamemode

### PR DESCRIPTION
**Pull request by rejedai**
I use gamemode with aggressive killing of processes unused for games. However, in some games I need some processes, so this way of disabling gamemode is extremely necessary.

### CODE REVIEW

**Comment by rejedai** [comment]
Also, some people complain about gamemode crashes in apex legends, so maybe this env would be nice to add to protonfixes.

**Comment by GloriousEggroll** [comment]
im removing it from the build, received more noise complaints than praise so its gone

**Comment by techmouse** [comment]
Is there a place where I can read some of these noise complaints? I would really like to know the downsides of gamemode.

**Comment by GloriousEggroll** [comment]
> Is there a place where I can read some of these noise complaints? I would really like to know the downsides of gamemode.

https://www.reddit.com/r/linux_gaming/comments/tvvzr2/geproton713_released/

I don't know what people do to their systems that would make gamemode freeze/crash it, but if thats happening they have bigger problems. Regardless, it's one of those touchy subjects I'd rather not make worse.

**Comment by techmouse** [comment]
Oh reddit huh? I thought it was going to be critique from a reputable voice of opinion.

This guy seems like he has some actual insight though and what he says would agree with your point.
https://old.reddit.com/r/linux_gaming/comments/tvvzr2/geproton713_released/i3f29tz/

But anyways. Since you're short on new praise and I have your attention, now is probably a wonderful time to mention that the latest builds got Cities XXL working!

This is great news because this is the first time Proton has ever gotten it to work in all of these years! Every time I see an update of any Proton, the first game I always test it with is Cities XXL and the day has finally come where it finally works!

At least I'm assuming this is thanks to you since it still doesn't work with Valve's official Proton 7 branch.

But there's still one issue; none of the resource overlays are working in the game. I'm guessing it's some kind of a texturing issue? What I can do to help resolve this?

**Comment by ryanmusante** [comment]
For tweaking this is basically all you need, separate from proton. Make it permanent, laptops included
https://wiki.archlinux.org/title/improving_performance

**Pull request closed without merging**
