### PR TITLE
Build proton on Github actions

### PR DESCRIPTION
**Pull request by vaslabs**
## Summary
- Proton is built on a mac 10.15 environment because it's the only one provided that has virtualisation (has VirtualBox and vagrant already installed)
- vagrant-sshfs requires a tty but it's not needed with virtual box so I commented it out.
- Build takes about 2 hours

## Prerequisites
- In order for the tarball and shasum to be uploaded to the release a personal access token is needed (named GH_PAT)

### Create personal access token
1. In Settings > Developer create new repository secret
access_token_screen

2. These are the permissions I gave to my secret (it probably doesn't need access to discussions, I had problems with another action related to goreleaser)

access_token_permissions1
access_token_permissions2

3. Copy the token value over to the project secrets

create_secret
 

It will be a good idea to test this before running the whole thing as it takes about two hours, this was my test : https://github.com/vaslabs/proton-ge-custom/blob/56f7c1898c1ea8927c17947024de95cb8302b7e4/.github/workflows/release.yml
 

## Results
- Successful workflow: https://github.com/vaslabs/proton-ge-custom/actions/runs/822623394
- Release: https://github.com/vaslabs/proton-ge-custom/releases/tag/6.7-GE-RC-16

### CODE REVIEW

**Comment by GloriousEggroll** [comment]
if possible I'd like to keep the sshfs plugin functionality. changing it every time i clone for a local build is not ideal, and will also cause issues with others who are not aware. people read readmes about as well as a blind baboon. apart from that I'd really like to get this merged, it's definitely a good idea.

**Comment by vaslabs** [comment]
True, I was thinking about it and we could just have another vagrant file dedicated to GitHub actions

**Comment by vaslabs** [comment]
Update:
- New, dedicated Vagrant.github file is used for github action
- Restored Vagrantfile to its previous state

**Comment by vaslabs** [comment]
@GloriousEggroll with the latest commits there's some issue compiling wine, do you have the same problem?

**Comment by vaslabs** [comment]
I might be wrong, but it looks like some of the patches are no longer compatible

**Comment by vaslabs** [comment]
All good again

**Pull request merged**
