### PR TITLE
patches: added Persona 5 Royal fix

### PR DESCRIPTION
**Pull request by lucasssvaz**
Patch for Persona 5 Royal. Semi-stub. Redirects deprecated, non-implemented calls for writing files to the correct ones.

Created by @Etaash-mathamsetty.

Fixes [this issue](https://github.com/ValveSoftware/Proton/issues/6255).

### CODE REVIEW

**Comment by AnonLibre** [comment]
I was able to build this version and run it successfully. The game starts, the save state is created, the configuration menu works, the intro is played.

```
git clone --recurse-submodules https://github.com/lucasssvaz/proton-ge-custom.git -b feature/p5r_patch ./ge-proton-persona-5-royal-patch
./patches/protonprep-valve-staging.sh &> patchlog.txt
./patches/protonprep-valve-staging.sh &> patchlog.txt
mkdir build && cd build
../configure.sh --enable-ccache --build-name=GE-Proton7-37-p5r --container-engine=docker
make redist &> log
tar -xf GE-Proton7-37-p5r.tar.gz -C "${HOME}/.steam/root/compatibilitytools.d/"
```

Thank you @Etaash-mathamsetty, @lucasssvaz, @GloriousEggroll and all who contributed.

**Comment by BananaWorks07** [comment]
I think you should update the patch with the one here [gitlab.winehq.org/wine/wine/-/merge_requests/1145](https://gitlab.winehq.org/wine/wine/-/merge_requests/1145), since it has been cleaned up and doesn't have a missing newline in some FIXME statements (whoops)

**Comment by lucasssvaz** [comment]
> I think you should update the patch with the one here [gitlab.winehq.org/wine/wine/-/merge_requests/1145](https://gitlab.winehq.org/wine/wine/-/merge_requests/1145), since it has been cleaned up and doesn't have a missing newline in some FIXME statements (whoops)

Force pushed the changes here based on your wine commit. Please, check if everything looks good and I didn't make any mistakes ^^

**Comment by okryp** [comment]
Apologies for bothering you all, but could someone link me a tarball with this build already build?
I've been trying to build it myself for almost 1,5 hours now without any luck.

**Comment by lucasssvaz** [comment]
> Apologies for bothering you all, but could someone link me a tarball with this build already build? I've been trying to build it myself for almost 1,5 hours now without any luck.

I think someone already did that [in the original issue.](https://github.com/ValveSoftware/Proton/issues/6255)

**Comment by AnonLibre** [comment]
> Please, check if everything looks good and I didn't make any mistakes
@lucasssvaz @Etaash-mathamsetty

The current version was successfully built on my system. I was able to start the game again, everything seems to be fine.

Title: GE-Proton7-37-p5r
Repo: https://github.com/lucasssvaz/proton-ge-custom/tree/feature/p5r_patch
Commit: dc086edcd1639cedefce69b743c86513f3e92dbc
Timestamp: 2022-10-23T00-46-25 CEST

@jrasb

Since I just tested and built the current version, I uploaded it in case you are still interested.

Download via WeTransfer: https://we.tl/t-H9TnXGc9tB

**sha512sum**
`622b0c0d8260a96d59d668dd5464d42cda91b0b8f074d1396eec48588820252f7f55c927c13c58bf92fc105124b62e48d6a5a47e18f06eb5a9345921178289d5  GE-Proton7-37-p5r.tar.gz`

[GE-Proton7-37-p5r.sha512sum.txt](https://github.com/GloriousEggroll/proton-ge-custom/files/9845392/GE-Proton7-37-p5r.sha512sum.txt)

**Comment by Steffo99** [comment]
Built successfully and played until April 11 with no problems! :rocket:

**Comment by GloriousEggroll** [comment]
handled in commit 8a0e5db9899b0c78aceea0eb8163b2a9645a2f9c

**Comment by ReillyBrogan** [comment]
@GloriousEggroll FYI it appears that both the comment in [patches/protonprep-valve-staging.sh](https://github.com/GloriousEggroll/proton-ge-custom/commit/8a0e5db9899b0c78aceea0eb8163b2a9645a2f9c#diff-9acf1beb275bea7d549e2af4ec474105e571890e5cfd4fb3277742bcd1c13183) and the commit message refer to the game as "Persona 5 Strikers" which is inaccurate. The correct game title that this fixes is "Persona 5 Royal" (which is a completely different game from Strikers) and you may want to correct the comment at least to prevent future confusion.

**Comment by andrebrait** [comment]
Hey there,

Just calling some attention to the fact just redirecting the transactional calls to their regular counterparts might cause save data corruption in the event of a write failing midway through it.

From [this page on alternatives to the transactional I/O API](https://learn.microsoft.com/en-us/windows/win32/fileio/deprecation-of-txf)

>Applications updating a single file with "document-like" data
>
> Many applications which deal with "document-like" data tend to load the entire document into memory, operate on it, and then write it back out to save the changes. The needed atomicity here is that the changes either are completely applied or not applied at all, as an inconsistent state would render the file corrupt. A common approach is to write the document to a new file, then replace the original file with the new one. One method to do this is with the ReplaceFile API.

**Comment by BananaWorks07** [comment]
> Hey there,
> 
> Just calling some attention to the fact just redirecting the transactional calls to their regular counterparts might cause save data corruption in the event of a write failing midway through it.
> 
> From [this page on alternatives to the transactional I/O API](https://learn.microsoft.com/en-us/windows/win32/fileio/deprecation-of-txf)
> 
> >Applications updating a single file with "document-like" data
> >
> > Many applications which deal with "document-like" data tend to load the entire document into memory, operate on it, and then write it back out to save the changes. The needed atomicity here is that the changes either are completely applied or not applied at all, as an inconsistent state would render the file corrupt. A common approach is to write the document to a new file, then replace the original file with the new one. One method to do this is with the ReplaceFile API.

I don't really see a way of doing this without finding a way to implement a transaction, which would require a lot of unnecessary work for what is a deprecated api. The only good reason to implement transactions fully would be when corruption is a major problem

**Comment by GloriousEggroll** [comment]
> Hey there,
> 
> Just calling some attention to the fact just redirecting the transactional calls to their regular counterparts might cause save data corruption in the event of a write failing midway through it.
> 
> From [this page on alternatives to the transactional I/O API](https://learn.microsoft.com/en-us/windows/win32/fileio/deprecation-of-txf)
> 
> > Applications updating a single file with "document-like" data
> > Many applications which deal with "document-like" data tend to load the entire document into memory, operate on it, and then write it back out to save the changes. The needed atomicity here is that the changes either are completely applied or not applied at all, as an inconsistent state would render the file corrupt. A common approach is to write the document to a new file, then replace the original file with the new one. One method to do this is with the ReplaceFile API.

might let valve know, we dont apply the patch anymore because they upstreamed it so its now included in proton-wine:

https://github.com/ValveSoftware/wine/commit/3ec22629d2154e75fe88148595d1640d5310fced

**Comment by andrebrait** [comment]
> I don't really see a way of doing this without finding a way to implement a transaction, which would require a lot of unnecessary work for what is a deprecated api. The only good reason to implement transactions fully would be when corruption is a major problem 

Well, if they're writing the entire file on a single call, it's supposedly equivalent to writing it to a separate file and then moving it at the end of writing.

Otherwise, I suppose one could implement "fake transactions" (i.e. the same process as above with state indicating the current transaction, possibly something local to the current thread or something, I suppose, then closing the transaction becomes moving the temporary file over to the actual file).

**Comment by BananaWorks07** [comment]
> > I don't really see a way of doing this without finding a way to implement a transaction, which would require a lot of unnecessary work for what is a deprecated api. The only good reason to implement transactions fully would be when corruption is a major problem
> 
> Well, if they're writing the entire file on a single call, it's supposedly equivalent to writing it to a separate file and then moving it at the end of writing.
> 
> Otherwise, I suppose one could implement "fake transactions" (i.e. the same process as above with state indicating the current transaction, possibly something local to the current thread or something, I suppose, then closing the transaction becomes moving the temporary file over to the actual file).

that sounds like a good implementation, but I don't see the need to spend time on it unless a software explicitly needs it, if we add it with no software using it, it becomes a maintenance burden on the wine developers.

**Pull request closed without merging**
