### PR TITLE
Easy-setup script

### PR DESCRIPTION
**Pull request by konsumer**
I made a quick easy-setup script that asks a couple questions and installs dependencies on an Ubunmtu system. I am open to expanding this to support more distros. Currently it uses flatpack for the most basic/easy setup, but I am fine with re-working it to use the "manual method" or something else. Main thing is having a single simple "curl pipe" to run, so it's very fast & simple to setup.

### CODE REVIEW

**Comment by GloriousEggroll** [comment]
Hi, sorry but I specifically do not include additional setup scripts in my repo because it means I have to maintain them across multiple distros, in addition to having to use flatpack for this version. There are already several different tools that exist to do this which work across multiple distros without the need for flatpak.

**Comment by konsumer** [comment]
No prob.

**Comment by GloriousEggroll** [comment]
No offense meant, it is a good idea, the support ability is just not something I can maintain

**Comment by konsumer** [comment]
Yep, I hear that. I [originally made it](https://gist.github.com/konsumer/56b0d05efc9a8296409b9da3f071e129) to solve my own problem (helping a linux noob install proton-ge on ubuntu machines very easily) but I definitely understand not wanting to support the multitude of edge-cases it will inevitably bring up.

If there are other better external tools for this, would it make sense to add them to the README?

**Pull request closed without merging**
