### PR TITLE
wine implemented VK_KHR_get_surface_capabilities2 to winevulkan

### PR DESCRIPTION
**Pull request by samedog**
Refer to https://github.com/wine-mirror/wine/commit/086c686e817a596e35c41dd5b37f3c28587af9d5

Btw Github keeps taking the whole file as pull because the line endings are messed in the original, i tried multiple times to no avail

### CODE REVIEW

**Comment by samedog** [comment]
the rabbit hole goes deeper on this one since part of the patch implements wine_vkGetPhysicalDeviceSurfaceCapabilities2KHR to toss out VkSurfaceFullScreenExclusiveInfoEXT i'm running some tests but i dunno where to actually submit this patches

**Comment by GloriousEggroll** [comment]
Hi Diego, I have a lot of local work including changes to go with upstream
wine that have not yet been committed. If you are going to compile from
source, I recommend compiling from the last release tag

**Comment by samedog** [comment]
ok gonna take a look

**Comment by GloriousEggroll** [comment]
closing, already updated

**Pull request closed without merging**
