### PR TITLE
FSR updated for proton 8

### PR DESCRIPTION
**Pull request by Ph42oN**
I made FSR patch for proton 8. It combines parts of previous fsr patches, only older fsr patch that will work with it is invert-fsr-logic.

Edit: I found that issue with fullscreen not working properly when fsr is disabled was present in proton 7, that is fixed in this version.

### CODE REVIEW

**Comment by GloriousEggroll** [comment]
hey just wanted to pop in and say thanks for this. I havent had time to review/test it but I just wanted to acknowledge I did see it come through my email. I will review it some time this week

**Comment by gabriele2000** [comment]
@Ph42oN would it be compatible with wine-tkg as patch?

**Comment by Ph42oN** [comment]
AFAIK, you have to use valve-exp or valve-exp-bleeding branch of wine for it to work. It uses proton fshack and it looks like there is no fshack for normal wine 8.x.

**Comment by gabriele2000** [comment]
Wine-tkg is a build system that allows you to build a customized wine
version (or proton version) which is basically patches + different folder
structures.

I think it would be possible and I wondered if it would be possible to use
it with wine-tkg build system.

I didn't know you didn't know what it was, sorry, my fault

**Comment by Ph42oN** [comment]
Yes i know i used wine-tkg script in testing this patch. Just select valve-exp or valve-exp-bleeding as wine version and it will work.

Edit: I actually tried, this patch didn't apply on valve branch, only valve-exp or valve-exp-bleeding. Not sure why its "48", i just used the same name it was. It may be something to do with order of applying patches.

**Comment by gabriele2000** [comment]
> Yes i know i used wine-tkg script in testing this patch. Just select valve-exp or valve-exp-bleeding as wine version and it will work.

Oh, ok, got it... Yeah, stupid question on my part, there's this "48" before the name so I figured out that it would've been the patch number for the hotfixer and stuff.

Later I've come to realize that this patch was on the "Proton specific patches" folder, digging into the wine-tkg "easy" configuration file revealed to me that it would work only on the "valve/valve exp" branch

**Comment by loathingKernel** [comment]
Could you consolidate the remaining patches in the FSR series into a single one? There seems to be things added in later patches missing. I don't mean everything, but what still makes sense. For example, since this FSR version can have FSR disabled, I don't see a point in forcing it on.

**Comment by Ph42oN** [comment]
What is missing? i fixed the bug where previous fsr patches caused fullscreen to not work properly when fsr is disabled. And some of things in those previous patches overwrite parts of other patches, this patch is using part that calculates the resolutions to add based on your resolution and can use custom resolutions.

**Comment by GloriousEggroll** [comment]
thanks for this again. I've just now gotten around to checking the patch itself. I didn't realized you'd also combined all of the previous patches except the invert logic one. I also see the manual resolutions that were added have been cleaned up and are calculated now using floating multipliers, this looks like it took a lot of work. Again, thanks and I'm sure the community will be thankful as well!

**Comment by loathingKernel** [comment]
> What is missing? i fixed the bug where previous fsr patches caused fullscreen to not work properly when fsr is disabled. And some of things in those previous patches overwrite parts of other patches, this patch is using part that calculates the resolutions to add based on your resolution and can use custom resolutions.

Sorry for the late reply, it slipped my mind and came back to me now that I needed FSR again. I had time to look into the parts of the patch that I have developed or worked on, which is the handling of the FSR resolutions mostly.

After a better look, my only pet peeve is that the patch is using only the naive division way to generate the resolutions. I would recommend for the way of guessing the aspect ratio and then computing the resolution to be added back. The non-naive way is less likely to produce resolutions with rounding errors. I tested both ways against the resolution list in Wikipedia and computing them based on aspect ratio consistently produced more accurate resolutions. The naive incorrectly rounded resolutions can cause blurriness, usually on fonts.

Edit: I just remembered another reason I opted for creating resolutions by first calculating the aspect ratio is because of games like Doom Eternal grouping resolutions by aspect ratio. Off-by-one resolutions can mess it up in a way that they won't be included in the available resolutions.

That being said, from what I have seen you have done an excellent job, kudos!

**Pull request merged**
