### PR TITLE
Add Nvidia Reflex patches.

### PR DESCRIPTION
**Pull request by loathingKernel**
The `vkd3d-proton` patch had to be rebased, nothing major though. Test build available [here](https://github.com/loathingKernel/Proton/actions/runs/6954519886) and [here](https://github.com/loathingKernel/Proton/releases/tag/GE-Proton8-25_nv_reflex) ~~soon(tm)~~

Requires at least Nvidia 545.xx drivers and `PROTON_ENABLE_NVAPI=1`.

The patches are from the following pull requests:
[wine](https://github.com/ValveSoftware/wine/pull/200)
[dxvk-nvapi](https://github.com/jp7677/dxvk-nvapi/pull/147)
[vkd3d-proton](https://github.com/HansKristian-Work/vkd3d-proton/pull/1739)
[dxvk](https://github.com/doitsujin/dxvk/pull/3690)

Thanks also goes to @ptr1337 for initially building and testing the patchset.

### CODE REVIEW

**Comment by ptr1337** [comment]
Don't forget that the Vulkan Headers for vkd3d and dxvk needs to be updated to commit `bbe0f575ebd6098369f0ac6c6a43532732ed0ba6` @GloriousEggroll

**Comment by loathingKernel** [comment]
> Don't forget that the Vulkan Headers for vkd3d and dxvk

I have added the required update to these libraries directly in [protonprep-valve-staging.sh](https://github.com/GloriousEggroll/proton-ge-custom/pull/104/commits/4925ecee84a13a48048cc3897aa18ebc23b1874f#diff-9acf1beb275bea7d549e2af4ec474105e571890e5cfd4fb3277742bcd1c13183) so it doesn't require any further intervention in that regard.

**Comment by Idcrafter** [comment]
i tried this build and in apex does it seem to work but not for Cyberpunk 2077 where it crashes when turning any option on with this in the console.

Assertion failed: !status && "vkGetLatencyTimingsNV", file ../src-wine/dlls/winev
ulkan/loader_thunks.c, line 4434

pid 901203 != 901202, skipping destruction (fork without exec?)

i have Nvidia 545.29.06 drivers and have the required vulkan extension for it.
my launch options: PROTON_ENABLE_NVAPI=1 PROTON_ENABLE_NGX_UPDATER=1 VKD3D_FEATURE_LEVEL=12_2 PROTON_HIDE_NVIDIA_GPU=0 VKD3D_CONFIG=dxr,force_static_cbv MANGOHUD=1 gamemoderun %command% --intro-skip --launcher-skip --skipStartScreen

**Comment by ParetoOptimalDev** [comment]
I can also confirm that this worked for me in that it let me enable reflex, but I still have stutters/etc.... I see the poster above has their launch options so I'll still those and see if they help.

My issues might be hyprland related though (even though I have the config patch).

**Comment by Idcrafter** [comment]
for more context i forgot is i use Fedora 39 with KDE Plasma 5.27.10 on Wayland.

**Comment by Weikugian** [comment]
Why did I get this email🤣



---Original---
From: ***@***.***&gt;
Date: Sat, Dec 30, 2023 12:05 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [GloriousEggroll/proton-ge-custom] Add Nvidia Reflex patches. (PR#104)




 
for more context i forgot is i use Fedora 39 with KDE Plasma 5.27.10 on Wayland.

**Comment by loathingKernel** [comment]
@Weikugian because of the way github resolves references to issues and PRs, the PRs in this repo are getting associated with issues on Valve's repo. It's a github problem.

**Comment by ParetoOptimalDev** [comment]
> I can also confirm that this worked for me in that it let me enable reflex, but I still have stutters/etc.... I see the poster above has their launch options so I'll still those and see if they help.
> 
> My issues might be hyprland related though (even though I have the config patch).

Wow, on KDE+X11 this makes all Apex Legends stuttering go away completely!

However it still has lag on:

- KDE / wayland
- hyprland /wayland

I don't think it's because of this PR, but perhaps a useful data point for future bug reports.

**Comment by ryanmusante** [comment]
Is "force_static_cbv" compatible with most games?

**Comment by ParetoOptimalDev** [comment]
> > I can also confirm that this worked for me in that it let me enable reflex, but I still have stutters/etc.... I see the poster above has their launch options so I'll still those and see if they help.
> > My issues might be hyprland related though (even though I have the config patch).
> 
> Wow, on KDE+X11 this makes all Apex Legends stuttering go away completely!
> 
> However it still has lag on:
> 
>     * KDE / wayland
> 
>     * hyprland /wayland
> 
> 
> I don't think it's because of this PR, but perhaps a useful data point for future bug reports.

Please let me know if anyone is running Apex or similar games with this stuttering issue on any wayland desktop environment or window manager too, since I'd prefer to use wayland if it doesn't have worse performance here.

**Comment by ryanmusante** [comment]
Are Nvidia 545.xx still.required or will the vulkan dev 535.xx be suitable?

**Comment by Idcrafter** [comment]
@ryanmusante if you have them installed then can you check if they work if this command returns 2 low_latency extensions:
`vulkaninfo | grep -i low_latency`

**Comment by Idcrafter** [comment]
@ParetoOptimalDev i do run Apex on wayland and get no stutters but i did not try it on X11 and am not able to test X11.

**Comment by Enderteck** [comment]
Is this implemented in GE-Proton-9.2 ?

I can't find the option on OW2. I'm on the latest Nvidia Drivers on Fedora 39 Gnome + Wayland.

PROTON_ENABLE_NVAPI=1 %command% on Steam doesn't change a thing

**Comment by ptr1337** [comment]
> Is this implemented in GE-Proton-9.2 ?
> 
> I can't find the option on OW2. I'm on the latest Nvidia Drivers on Fedora 39 Gnome + Wayland.
> 
> PROTON_ENABLE_NVAPI=1 %command% on Steam doesn't change a thing

No

**Comment by Enderteck** [comment]
Sadge 

wasn't it released nearly two weeks before tho ?

**Pull request merged**
